name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        show-progress: "false"
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Check go fmt
      run: |
        gofmt -l -s -w .
        git diff --exit-code

    - name: Build
      run: go build -v ./...

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        cache: yarn
        cache-dependency-path: lemmy-js-client/yarn.lock

    - name: Generate docs.json
      working-directory: lemmy-js-client
      run: |
        yarn install
        yarn run docs --json ../docs.json

    - name: Generate Lemmy API code
      run: go run cmd/gen/main.go -json-file docs.json -out-dir .

    - name: Check that generated files are not changed
      run: git diff --exit-code
